### ISSUE TITLE
Process-id failed

### ISSUE THREAD

**Issue by ridernl** [TKazer/Apex_External#2]
Keeps saying Process-id failed 

The thread 0x4b0c has exited with code 0 (0x0).
The thread 0x3660 has exited with code 0 (0x0).
'Apex_External.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'Apex_External.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
The thread 0x503c has exited with code 0 (0x0).
The program '[16644] Apex_External.exe' has exited with code 0 (0x0).

**Comment by TKazer** [comment]
> Keeps saying Process-id failed
> 
> The thread 0x4b0c has exited with code 0 (0x0). The thread 0x3660 has exited with code 0 (0x0). 'Apex_External.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 'Apex_External.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. The thread 0x503c has exited with code 0 (0x0). The program '[16644] Apex_External.exe' has exited with code 0 (0x0).

you should run it after game, it will fail if the game process does not exist.

**Comment by ridernl** [comment]
> 

I was an idiot :P
Thank you! it is running now, figuring the keys etc as i write this back :P
