### ISSUE TITLE
关于透视

### ISSUE THREAD

**Issue by xiaonian233** [TKazer/Apex_External#3]
老哥，这个GLOW有几句没整明白，能否给解答解答
![image](https://user-images.githubusercontent.com/21072615/184574213-838a1f63-ca5e-403a-b5c2-54cbba2b3429.png)
我记得常规透视写个glowtype然后写颜色就结束了，这三句上面部分都能明白，不知道这三句作用

**Comment by TKazer** [comment]
> 老哥，这个GLOW有几句没整明白，能否给解答解答 ![image](https://user-images.githubusercontent.com/21072615/184574213-838a1f63-ca5e-403a-b5c2-54cbba2b3429.png) 我记得常规透视写个glowtype然后写颜色就结束了，这三句上面部分都能明白，不知道这三句作用

GLOW实现这部分代码不是我写的，我只是写代码架构的。
