### ISSUE TITLE
Running, but does not work

### ISSUE THREAD

**Issue by ridernl** [TKazer/Apex_External#4]
Got it to run, but it does nothing in the game.
Am i missing a key combo, or is it not working?

Playing on steam btw, dont know if that changes anything

**Comment by TKazer** [comment]
> 

oh i use my own driver and i did not shared driver.h, so as you see, the ApDriver.h is empty. this source just used to study how to write a simple apex esp&aimbot , you need to change the read&write functions before use if you want to run it.

**Comment by ridernl** [comment]
Ahh i see! That is a part i still have to learn now hahahaha.
Thanks!
